# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='text',
            new_name='input_text',
        ),
    ]
