# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 19:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160102_0415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='inputOptions',
        ),
        migrations.AddField(
            model_name='options',
            name='summary_text',
            field=models.CharField(default=datetime.datetime(2016, 1, 2, 19, 27, 54, 966054, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
