# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20160104_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='n_size',
            field=models.CharField(choices=[('Unigram', '1'), ('Bigram', '2'), ('Trigram', '3')], default=('Unigram', '1'), max_length=1),
        ),
    ]
